### ISSUE TITLE
[OoB_RC1_5.4]: BLEURIBeacon fails to advertise itself. Cannot be detected on Physical web app.

### ISSUE THREAD

**Issue by ashok-rao** [ARMmbed/mbed-os-example-ble#62]
Steps to reproduce:
1. Clone the example, update to mbed OoB branch. Install Android app. (Using version 0.2.1 - updated from Google)
2. mbed compile -t ARM -m  nRF51_DK
3. Flash hex file, scan for beacons with the app.

Result:
The target enters config mode and exits after 60 sec but beacon cannot be detected on app.

Detailed description:
Using a generic BLE scanner app, the beacon is first detected in config mode (after reset). After 60 seconds or so, the beacon still is detected in config mode. The Physical web app does not detect any nearby beacons even after >120 sec

Edit: Issue also seen with GCC and IAR compilers.

**Comment by ashok-rao** [comment]
@pan- .. any ideas? Thanks.

**Comment by pan-** [comment]
@ashok-rao Apparently, google cut the support of URI beacon last august (see [here](https://github.com/google/physical-web/pull/774)). The update including this code hit the Google playstore last quarter. That's why URIBeacons are not visible anymore. 

> After 60 seconds or so, the beacon still is detected in config mode.
Using nRF connect, I see the mode of the beacon changing after 60 seconds.

I'm not sure of what we should do here. Maybe ending the life of this example is the right thing to do since the protocol has been abandoned and fully replace by Eddystone.

@sg- any thoughts ?

**Comment by ashok-rao** [comment]
Oh, OK. Thanks @pan- . Looks like the URIBeacon is fully replaced by Eddystone. http://google.github.io/uribeacon/

**Comment by sg-** [comment]
I'd suggest we remove that example.

**Comment by MarceloSalazar** [comment]
@pan- could you please remove the URI beacon example in the OOB branch?

**Comment by pan-** [comment]
Done, I close this.
